server:
  host: "0.0.0.0"
  port: 8082

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "changeme"
  dbname: "homecloud"
  sslmode: "disable"

storage:
  base_path: "/app/storage"
  max_size: 1073741824
  chunk_size: 1048576
  temp_path: "/app/temp"
  user_dir_name: "users"

logger:
  level: "info"
  development: true
  encoding: "console"
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    timeKey: "timestamp"
    nameKey: "logger"
    callerKey: "caller"
    functionKey: "func"
    stacktraceKey: "stacktrace"
    lineEnding: "\n"
    levelEncoder: "lowercase"
    timeEncoder: "iso8601"
    durationEncoder: "string"
    callerEncoder: "short" 

auth:
  host: "auth"
  port: 50052

dbmanager:
  host: "dbmanager"
  port: 50051

grpc:
  host: "0.0.0.0"
  port: 50053 